PR to merge latest simulation changes
vagechirkov/IceFishingABM-MESA pull request #7
Opened 2024-12-20 09:29 UTC by debapratimj

-  Alpha convention fixed
-  HTML fig saving 
- Added first passage time, step size stats
- Hyperparameters for 3 coupling/social info quality cases 
- Changes  in agent.py, model.py to add some functionalities

2024-12-20 10:14 UTC, vagechirkov commented
Hey @debapratimj, thanks for the updates! Please exclude results (database) from PR

2024-12-20 15:43 UTC, vagechirkov commented
Request for changes:
- Separate experiment execution and plotting;
- modularize the plotting code (i.e., make the plotting function for the non-optuna figures)
- add study name to `optuna.create_study` for easier navigation in the dashboard

2024-12-20 15:46 UTC, vagechirkov commented on experiments/experiment_071224_rw_default_no_coupling.py
> +    if plotting:
For this and all other experiments, all code below this line should not be in this file

2024-12-20 15:49 UTC, vagechirkov requested changes
- Separate experiment execution and plotting;
- modularize the plotting code (i.e., make the plotting function for the non-optuna figures)
- add study name to `optuna.create_study` for easier navigation in the dashboard

2025-01-07 13:52 UTC, debapratimj commented on experiments/experiment_071224_rw_default_no_coupling.py
> +    if plotting:
acceoted changes

2025-09-18 14:23 UTC, merged